# Generated by Django 5.1.4 on 2024-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song_title', models.CharField(max_length=50)),
                ('artist_name', models.CharField(max_length=50)),
                ('solo_or_group', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('year_released', models.IntegerField(max_length=50)),
            ],
        ),
    ]
